// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVqy9dHJGWhnNBwMafbcmKiWOjMrBChyE',
    appId: '1:252282139633:web:977adc6bbbe6c34c704a50',
    messagingSenderId: '252282139633',
    projectId: 'rmutl-testproject',
    authDomain: 'rmutl-testproject.firebaseapp.com',
    storageBucket: 'rmutl-testproject.firebasestorage.app',
    measurementId: 'G-G27871BWEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuJzg-Ax8W3zq55p-6n0ff3EBZSzPhzOI',
    appId: '1:252282139633:android:30ef367f920f8765704a50',
    messagingSenderId: '252282139633',
    projectId: 'rmutl-testproject',
    storageBucket: 'rmutl-testproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgh34r3NCFYSEnioUsQdQAQQ9FvcRqJr8',
    appId: '1:252282139633:ios:31c1278606cfd302704a50',
    messagingSenderId: '252282139633',
    projectId: 'rmutl-testproject',
    storageBucket: 'rmutl-testproject.firebasestorage.app',
    iosBundleId: 'com.example.rmutlTestproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgh34r3NCFYSEnioUsQdQAQQ9FvcRqJr8',
    appId: '1:252282139633:ios:31c1278606cfd302704a50',
    messagingSenderId: '252282139633',
    projectId: 'rmutl-testproject',
    storageBucket: 'rmutl-testproject.firebasestorage.app',
    iosBundleId: 'com.example.rmutlTestproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVqy9dHJGWhnNBwMafbcmKiWOjMrBChyE',
    appId: '1:252282139633:web:956aed4e94af6420704a50',
    messagingSenderId: '252282139633',
    projectId: 'rmutl-testproject',
    authDomain: 'rmutl-testproject.firebaseapp.com',
    storageBucket: 'rmutl-testproject.firebasestorage.app',
    measurementId: 'G-JVREHD6NC7',
  );
}
